services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DOCKER_CONTAINER=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vitodb
      - SPRING_DATASOURCE_USERNAME=postgres1
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - STRIPE_API_KEY=sk_test_51XYZabc123
    networks:
      - vitotrips-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=vitodb
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - vitotrips-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - vitotrips-network

networks:
  vitotrips-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: 