name: VitoTrips CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: vitodb_test
          POSTGRES_USER: postgres1
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn test
    
    - name: Build and analyze with SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=vitotrips
    
    - name: Build Docker image
      run: docker build -t vitotrips:${{ github.sha }} .
    
    - name: Save Docker image
      run: docker save vitotrips:${{ github.sha }} > vitotrips.tar
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vitotrips-docker-image
        path: vitotrips.tar
  
  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: vitotrips-docker-image
    
    - name: Load Docker image
      run: docker load < vitotrips.tar
    
    - name: Deploy to development environment
      run: |
        echo "Deploying to development environment..."
        # Add deployment commands here
  
  deploy-prod:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: vitotrips-docker-image
    
    - name: Load Docker image
      run: docker load < vitotrips.tar
    
    - name: Deploy to production environment
      run: |
        echo "Deploying to production environment..."
        # Add production deployment commands here 